name: Pack
on:
    workflow_dispatch:
    release:
      types: [published]
jobs:
    pack-on-release:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2  
          - name: Pack
            run: |
                dotnet nuget add source "https://nuget.pkg.github.com/VORNIR/index.json" --name "github" --username "${{ secrets.USERNAME }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text
                dotnet pack --configuration Release  --output .
          - name: Push
            run: dotnet nuget push ${{ github.event.repository.name }}.*.nupkg --source https://nuget.pkg.github.com/VORNIR/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
